// Automatically generated by MockGen. DO NOT EDIT!
// Source: output.go

package mock_gotable

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Output interface
type MockOutput struct {
	ctrl     *gomock.Controller
	recorder *_MockOutputRecorder
}

// Recorder for MockOutput (not exported)
type _MockOutputRecorder struct {
	mock *MockOutput
}

func NewMockOutput(ctrl *gomock.Controller) *MockOutput {
	mock := &MockOutput{ctrl: ctrl}
	mock.recorder = &_MockOutputRecorder{mock}
	return mock
}

func (_m *MockOutput) EXPECT() *_MockOutputRecorder {
	return _m.recorder
}

func (_m *MockOutput) Print(_param0 string) {
	_m.ctrl.Call(_m, "Print", _param0)
}

func (_mr *_MockOutputRecorder) Print(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Print", arg0)
}
